num = int(input('Digite seu número: '))

tabuada1 = num*1, num*2, num*3, num*4, num*5, num*6, num*7, num*8, num*9, num*10
print("------------")
print(f"Tabuada de multipicação {num}: 1 até 10: {tabuada1}")
print("Ou...")
print(f"{num}, 1, {num * 1}")
print(f"{num}, 2, {num * 2}")
print(f"{num}, 3, {num * 3}")
print(f"{num}, 4, {num * 4}")
print(f"{num}, 5, {num * 5}")
print(f"{num}, 5, {num * 6}")
print(f"{num}, 7, {num * 7}")
print(f"{num}, 8, {num * 8}")
print(f"{num}, 9, {num * 9}")
print(f"{num}, 10, {num * 10}")
print("-------------")